### ISSUE TITLE
[BUG] Some raw repos have no `text2git` option and therefore some info are not retrieved automatically from metadeta

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/Datasets#5]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- OS:
- Matlab:
- SPM:
```

### Branch

```markdown
- branch:
- version:
```

**Comment by Remi-Gau** [comment]
I have updated the config of all raw datasets to avoid this probelm but the content may still be in the annex so we would have to get it out of there.

Can you make a listing of the problematic datasets?

**Comment by Remi-Gau** [comment]
Relevant section of the handbook: https://handbook.datalad.org/en/latest/basics/101-136-filesystem.html#getting-contents-out-of-git-annex

**Comment by Remi-Gau** [comment]
should be fixed
make sure to update the repo and the subdatasets before rerunning any scripts
